// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiccAD95hhzBv2jiZoVov530rbLpFv-_M',
    appId: '1:311034727337:web:85d2beb1448bff4fd192b8',
    messagingSenderId: '311034727337',
    projectId: 'todo-app-7519b',
    authDomain: 'todo-app-7519b.firebaseapp.com',
    storageBucket: 'todo-app-7519b.appspot.com',
    measurementId: 'G-6SZ58VCY67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvoAfrV3htiNoMBShSqBYolFrW1wnj1sk',
    appId: '1:311034727337:android:03dc7d3d39ac36e8d192b8',
    messagingSenderId: '311034727337',
    projectId: 'todo-app-7519b',
    storageBucket: 'todo-app-7519b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiccAD95hhzBv2jiZoVov530rbLpFv-_M',
    appId: '1:311034727337:web:4b29b3766e287890d192b8',
    messagingSenderId: '311034727337',
    projectId: 'todo-app-7519b',
    authDomain: 'todo-app-7519b.firebaseapp.com',
    storageBucket: 'todo-app-7519b.appspot.com',
    measurementId: 'G-XE7GQHCXYF',
  );
}
